// COLOR CODES
let FIREBRICK = "#B22222"
let CHARTREUSE = "#7FFF00"
let MEDIUMAQUAMARINE = "#66CDAA"

// MEMENTO COLORS

let MEM_RED = "#B22222";
let MEM_GREEN = "#669966";
let MEM_BLUE = "#4D66CC";
let MEM_LIGHT_GREEN = "#CCFFCC"
let MEM_LIGHT_YELLOW = "#FFFFCC"
let MEM_LIGHT_BLUE = "#CCFFFF"
